/*
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BookingManagementApi
 */
@Disabled
public class BookingManagementApiTest {

    private final BookingManagementApi api = new BookingManagementApi();

    /**
     * Cancel booking
     *
     * This endpoint allows you to cancel a booking based on a booking ID. The refund amount is based on the cancellation policies. &lt;!-- theme: danger --&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingsBookingIdDeleteTest() throws ApiException {
        String bookingId = null;
        Object response = api.bookingsBookingIdDelete(bookingId);
        // TODO: test validations
    }

    /**
     * Retrieve booking
     *
     * This endpoint allows you to retrieve all the information for specific booking ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingsBookingIdGetTest() throws ApiException {
        String bookingId = null;
        Object response = api.bookingsBookingIdGet(bookingId);
        // TODO: test validations
    }

}
