/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.HotelRates200Response;
import org.openapitools.client.model.HotelsSearch200Response;
import org.openapitools.client.model.HotelsSearch400Response;
import org.openapitools.client.model.HotelsSearch401Response;
import org.openapitools.client.model.HotelsSearchRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HotelsApi
 */
@Disabled
public class HotelsApiTest {

    private final HotelsApi api = new HotelsApi();

    /**
     * hotel rates
     *
     * hotel rates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void hotelRatesTest() throws ApiException {
        String hotelId = null;
        String checkin = null;
        String checkout = null;
        String adults = null;
        String children = null;
        String guestNationality = null;
        String currency = null;
        String sessionId = null;
        String rid = null;
        String xid = null;
        HotelRates200Response response = api.hotelRates(hotelId, checkin, checkout, adults, children, guestNationality, currency, sessionId, rid, xid);
        // TODO: test validations
    }

    /**
     * hotels search
     *
     * hotels search
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void hotelsSearchTest() throws ApiException {
        String rid = null;
        HotelsSearchRequest hotelsSearchRequest = null;
        HotelsSearch200Response response = api.hotelsSearch(rid, hotelsSearchRequest);
        // TODO: test validations
    }

}
