/**
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HotelsPostRequest {
  
  @SerializedName("checkin")
  private String checkin = null;
  @SerializedName("checkout")
  private String checkout = null;
  @SerializedName("latitude")
  private BigDecimal latitude = null;
  @SerializedName("longitude")
  private BigDecimal longitude = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("distance")
  private Integer distance = null;
  @SerializedName("adults")
  private Integer adults = null;
  @SerializedName("children")
  private String children = null;
  @SerializedName("currency")
  private String currency = null;
  @SerializedName("guestNationality")
  private String guestNationality = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCheckin() {
    return checkin;
  }
  public void setCheckin(String checkin) {
    this.checkin = checkin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCheckout() {
    return checkout;
  }
  public void setCheckout(String checkout) {
    this.checkout = checkout;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getLatitude() {
    return latitude;
  }
  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getLongitude() {
    return longitude;
  }
  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDistance() {
    return distance;
  }
  public void setDistance(Integer distance) {
    this.distance = distance;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAdults() {
    return adults;
  }
  public void setAdults(Integer adults) {
    this.adults = adults;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChildren() {
    return children;
  }
  public void setChildren(String children) {
    this.children = children;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGuestNationality() {
    return guestNationality;
  }
  public void setGuestNationality(String guestNationality) {
    this.guestNationality = guestNationality;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelsPostRequest hotelsPostRequest = (HotelsPostRequest) o;
    return (this.checkin == null ? hotelsPostRequest.checkin == null : this.checkin.equals(hotelsPostRequest.checkin)) &&
        (this.checkout == null ? hotelsPostRequest.checkout == null : this.checkout.equals(hotelsPostRequest.checkout)) &&
        (this.latitude == null ? hotelsPostRequest.latitude == null : this.latitude.equals(hotelsPostRequest.latitude)) &&
        (this.longitude == null ? hotelsPostRequest.longitude == null : this.longitude.equals(hotelsPostRequest.longitude)) &&
        (this.country == null ? hotelsPostRequest.country == null : this.country.equals(hotelsPostRequest.country)) &&
        (this.distance == null ? hotelsPostRequest.distance == null : this.distance.equals(hotelsPostRequest.distance)) &&
        (this.adults == null ? hotelsPostRequest.adults == null : this.adults.equals(hotelsPostRequest.adults)) &&
        (this.children == null ? hotelsPostRequest.children == null : this.children.equals(hotelsPostRequest.children)) &&
        (this.currency == null ? hotelsPostRequest.currency == null : this.currency.equals(hotelsPostRequest.currency)) &&
        (this.guestNationality == null ? hotelsPostRequest.guestNationality == null : this.guestNationality.equals(hotelsPostRequest.guestNationality));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.checkin == null ? 0: this.checkin.hashCode());
    result = 31 * result + (this.checkout == null ? 0: this.checkout.hashCode());
    result = 31 * result + (this.latitude == null ? 0: this.latitude.hashCode());
    result = 31 * result + (this.longitude == null ? 0: this.longitude.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.distance == null ? 0: this.distance.hashCode());
    result = 31 * result + (this.adults == null ? 0: this.adults.hashCode());
    result = 31 * result + (this.children == null ? 0: this.children.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.guestNationality == null ? 0: this.guestNationality.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelsPostRequest {\n");
    
    sb.append("  checkin: ").append(checkin).append("\n");
    sb.append("  checkout: ").append(checkout).append("\n");
    sb.append("  latitude: ").append(latitude).append("\n");
    sb.append("  longitude: ").append(longitude).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  distance: ").append(distance).append("\n");
    sb.append("  adults: ").append(adults).append("\n");
    sb.append("  children: ").append(children).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  guestNationality: ").append(guestNationality).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
