/**
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookingRetrieve400ResponseError from './BookingRetrieve400ResponseError';

/**
 * The BookingRetrieve400Response model module.
 * @module model/BookingRetrieve400Response
 * @version 1.0.0
 */
class BookingRetrieve400Response {
    /**
     * Constructs a new <code>BookingRetrieve400Response</code>.
     * @alias module:model/BookingRetrieve400Response
     */
    constructor() { 
        
        BookingRetrieve400Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookingRetrieve400Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookingRetrieve400Response} obj Optional instance to populate.
     * @return {module:model/BookingRetrieve400Response} The populated <code>BookingRetrieve400Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookingRetrieve400Response();

            if (data.hasOwnProperty('error')) {
                obj['error'] = BookingRetrieve400ResponseError.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookingRetrieve400Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookingRetrieve400Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `error`
        if (data['error']) { // data not null
          BookingRetrieve400ResponseError.validateJSON(data['error']);
        }

        return true;
    }


}



/**
 * @member {module:model/BookingRetrieve400ResponseError} error
 */
BookingRetrieve400Response.prototype['error'] = undefined;






export default BookingRetrieve400Response;

