/**
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HotelsSearch200ResponseDataInner model module.
 * @module model/HotelsSearch200ResponseDataInner
 * @version 1.0.0
 */
class HotelsSearch200ResponseDataInner {
    /**
     * Constructs a new <code>HotelsSearch200ResponseDataInner</code>.
     * @alias module:model/HotelsSearch200ResponseDataInner
     */
    constructor() { 
        
        HotelsSearch200ResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HotelsSearch200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HotelsSearch200ResponseDataInner} obj Optional instance to populate.
     * @return {module:model/HotelsSearch200ResponseDataInner} The populated <code>HotelsSearch200ResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HotelsSearch200ResponseDataInner();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('hotelId')) {
                obj['hotelId'] = ApiClient.convertToType(data['hotelId'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HotelsSearch200ResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HotelsSearch200ResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['hotelId'] && !(typeof data['hotelId'] === 'string' || data['hotelId'] instanceof String)) {
            throw new Error("Expected the field `hotelId` to be a primitive type in the JSON string but got " + data['hotelId']);
        }

        return true;
    }


}



/**
 * @member {String} currency
 */
HotelsSearch200ResponseDataInner.prototype['currency'] = undefined;

/**
 * @member {String} hotelId
 */
HotelsSearch200ResponseDataInner.prototype['hotelId'] = undefined;

/**
 * @member {Number} price
 */
HotelsSearch200ResponseDataInner.prototype['price'] = undefined;






export default HotelsSearch200ResponseDataInner;

