/**
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner from './RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner';

/**
 * The RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies model module.
 * @module model/RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies
 * @version 1.0.0
 */
class RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies {
    /**
     * Constructs a new <code>RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies</code>.
     * @alias module:model/RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies
     */
    constructor() { 
        
        RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies} obj Optional instance to populate.
     * @return {module:model/RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies} The populated <code>RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies();

            if (data.hasOwnProperty('cancelPolicyInfos')) {
                obj['cancelPolicyInfos'] = ApiClient.convertToType(data['cancelPolicyInfos'], [RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner]);
            }
            if (data.hasOwnProperty('hotelRemarks')) {
                obj['hotelRemarks'] = ApiClient.convertToType(data['hotelRemarks'], [Object]);
            }
            if (data.hasOwnProperty('refundableTag')) {
                obj['refundableTag'] = ApiClient.convertToType(data['refundableTag'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies</code>.
     */
    static validateJSON(data) {
        if (data['cancelPolicyInfos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cancelPolicyInfos'])) {
                throw new Error("Expected the field `cancelPolicyInfos` to be an array in the JSON data but got " + data['cancelPolicyInfos']);
            }
            // validate the optional field `cancelPolicyInfos` (array)
            for (const item of data['cancelPolicyInfos']) {
                RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner.validateJsonObject(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['hotelRemarks'])) {
            throw new Error("Expected the field `hotelRemarks` to be an array in the JSON data but got " + data['hotelRemarks']);
        }
        // ensure the json data is a string
        if (data['refundableTag'] && !(typeof data['refundableTag'] === 'string' || data['refundableTag'] instanceof String)) {
            throw new Error("Expected the field `refundableTag` to be a primitive type in the JSON string but got " + data['refundableTag']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner>} cancelPolicyInfos
 */
RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.prototype['cancelPolicyInfos'] = undefined;

/**
 * @member {Array.<Object>} hotelRemarks
 */
RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.prototype['hotelRemarks'] = undefined;

/**
 * @member {String} refundableTag
 */
RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.prototype['refundableTag'] = undefined;






export default RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies;

