/**
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RateBook200ResponseDataCancellationFee from './RateBook200ResponseDataCancellationFee';

/**
 * The RateBook200ResponseDataCancellation model module.
 * @module model/RateBook200ResponseDataCancellation
 * @version 1.0.0
 */
class RateBook200ResponseDataCancellation {
    /**
     * Constructs a new <code>RateBook200ResponseDataCancellation</code>.
     * @alias module:model/RateBook200ResponseDataCancellation
     */
    constructor() { 
        
        RateBook200ResponseDataCancellation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RateBook200ResponseDataCancellation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RateBook200ResponseDataCancellation} obj Optional instance to populate.
     * @return {module:model/RateBook200ResponseDataCancellation} The populated <code>RateBook200ResponseDataCancellation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RateBook200ResponseDataCancellation();

            if (data.hasOwnProperty('fee')) {
                obj['fee'] = RateBook200ResponseDataCancellationFee.constructFromObject(data['fee']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RateBook200ResponseDataCancellation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RateBook200ResponseDataCancellation</code>.
     */
    static validateJSON(data) {
        // validate the optional field `fee`
        if (data['fee']) { // data not null
          RateBook200ResponseDataCancellationFee.validateJSON(data['fee']);
        }

        return true;
    }


}



/**
 * @member {module:model/RateBook200ResponseDataCancellationFee} fee
 */
RateBook200ResponseDataCancellation.prototype['fee'] = undefined;






export default RateBook200ResponseDataCancellation;

