/**
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RateBook200ResponseDataBookedRoomsInnerRate from './RateBook200ResponseDataBookedRoomsInnerRate';
import RateBook200ResponseDataBookedRoomsInnerRoomType from './RateBook200ResponseDataBookedRoomsInnerRoomType';

/**
 * The RateBook200ResponseDataBookedRoomsInner model module.
 * @module model/RateBook200ResponseDataBookedRoomsInner
 * @version 1.0.0
 */
class RateBook200ResponseDataBookedRoomsInner {
    /**
     * Constructs a new <code>RateBook200ResponseDataBookedRoomsInner</code>.
     * @alias module:model/RateBook200ResponseDataBookedRoomsInner
     */
    constructor() { 
        
        RateBook200ResponseDataBookedRoomsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RateBook200ResponseDataBookedRoomsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RateBook200ResponseDataBookedRoomsInner} obj Optional instance to populate.
     * @return {module:model/RateBook200ResponseDataBookedRoomsInner} The populated <code>RateBook200ResponseDataBookedRoomsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RateBook200ResponseDataBookedRoomsInner();

            if (data.hasOwnProperty('adults')) {
                obj['adults'] = ApiClient.convertToType(data['adults'], 'Number');
            }
            if (data.hasOwnProperty('children')) {
                obj['children'] = ApiClient.convertToType(data['children'], 'Number');
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = RateBook200ResponseDataBookedRoomsInnerRate.constructFromObject(data['rate']);
            }
            if (data.hasOwnProperty('roomType')) {
                obj['roomType'] = RateBook200ResponseDataBookedRoomsInnerRoomType.constructFromObject(data['roomType']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RateBook200ResponseDataBookedRoomsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RateBook200ResponseDataBookedRoomsInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `rate`
        if (data['rate']) { // data not null
          RateBook200ResponseDataBookedRoomsInnerRate.validateJSON(data['rate']);
        }
        // validate the optional field `roomType`
        if (data['roomType']) { // data not null
          RateBook200ResponseDataBookedRoomsInnerRoomType.validateJSON(data['roomType']);
        }

        return true;
    }


}



/**
 * @member {Number} adults
 */
RateBook200ResponseDataBookedRoomsInner.prototype['adults'] = undefined;

/**
 * @member {Number} children
 */
RateBook200ResponseDataBookedRoomsInner.prototype['children'] = undefined;

/**
 * @member {module:model/RateBook200ResponseDataBookedRoomsInnerRate} rate
 */
RateBook200ResponseDataBookedRoomsInner.prototype['rate'] = undefined;

/**
 * @member {module:model/RateBook200ResponseDataBookedRoomsInnerRoomType} roomType
 */
RateBook200ResponseDataBookedRoomsInner.prototype['roomType'] = undefined;






export default RateBook200ResponseDataBookedRoomsInner;

