/**
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner from './RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner';

/**
 * The RateBook200ResponseDataCancellationPolicies model module.
 * @module model/RateBook200ResponseDataCancellationPolicies
 * @version 1.0.0
 */
class RateBook200ResponseDataCancellationPolicies {
    /**
     * Constructs a new <code>RateBook200ResponseDataCancellationPolicies</code>.
     * @alias module:model/RateBook200ResponseDataCancellationPolicies
     */
    constructor() { 
        
        RateBook200ResponseDataCancellationPolicies.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RateBook200ResponseDataCancellationPolicies</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RateBook200ResponseDataCancellationPolicies} obj Optional instance to populate.
     * @return {module:model/RateBook200ResponseDataCancellationPolicies} The populated <code>RateBook200ResponseDataCancellationPolicies</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RateBook200ResponseDataCancellationPolicies();

            if (data.hasOwnProperty('cancelPolicyInfos')) {
                obj['cancelPolicyInfos'] = ApiClient.convertToType(data['cancelPolicyInfos'], [RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner]);
            }
            if (data.hasOwnProperty('hotelRemarks')) {
                obj['hotelRemarks'] = ApiClient.convertToType(data['hotelRemarks'], [Object]);
            }
            if (data.hasOwnProperty('refundableTag')) {
                obj['refundableTag'] = ApiClient.convertToType(data['refundableTag'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RateBook200ResponseDataCancellationPolicies</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RateBook200ResponseDataCancellationPolicies</code>.
     */
    static validateJSON(data) {
        if (data['cancelPolicyInfos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cancelPolicyInfos'])) {
                throw new Error("Expected the field `cancelPolicyInfos` to be an array in the JSON data but got " + data['cancelPolicyInfos']);
            }
            // validate the optional field `cancelPolicyInfos` (array)
            for (const item of data['cancelPolicyInfos']) {
                RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner.validateJsonObject(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['hotelRemarks'])) {
            throw new Error("Expected the field `hotelRemarks` to be an array in the JSON data but got " + data['hotelRemarks']);
        }
        // ensure the json data is a string
        if (data['refundableTag'] && !(typeof data['refundableTag'] === 'string' || data['refundableTag'] instanceof String)) {
            throw new Error("Expected the field `refundableTag` to be a primitive type in the JSON string but got " + data['refundableTag']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner>} cancelPolicyInfos
 */
RateBook200ResponseDataCancellationPolicies.prototype['cancelPolicyInfos'] = undefined;

/**
 * @member {Array.<Object>} hotelRemarks
 */
RateBook200ResponseDataCancellationPolicies.prototype['hotelRemarks'] = undefined;

/**
 * @member {String} refundableTag
 */
RateBook200ResponseDataCancellationPolicies.prototype['refundableTag'] = undefined;






export default RateBook200ResponseDataCancellationPolicies;

