/**
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NliteApi);
  }
})(this, function (expect, NliteApi) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new NliteApi.BookingsApi();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("BookingsApi", function () {
    // describe("bookingCancel", function () {
    //   it("should call bookingCancel successfully", function (done) {
    //     // instance.bookingCancel(function (error) {
    //     //   if (error) throw error;
    //     //   expect().to.be();
    //     // });
    //     // done();
    //   });
    // });
    // describe("bookingRetrieve", function () {
    //   it("should call bookingRetrieve successfully", function (done) {
    //     //uncomment below and update the code to test bookingRetrieve
    //     //instance.bookingRetrieve(function(error) {
    //     //  if (error) throw error;
    //     //expect().to.be();
    //     //});
    //     done();
    //   });
    // });
    describe("rateBook", function () {
      it("should call rateBook successfully", function (done) {
        let options = {
          body: {
            prebookId: "uWPR0yV8M",
            sessionId:
              "GIYDEMZNGAZS2MJVPQZDAMRTFUYDGLJRGZ6DC7BRGIWDS7CNIF6HYMLEMRWV6Z3EKNXGC",
            contact: {
              firstName: "fname",
              lastName: "lname",
              email: "test@test.test",
            },
            rateId:
              "2_4AJJDS635YOKR4HO6LMEPTCNH5MO3ALKOOQBIMRW7XM6UMOC7TNFPJPYOJTLBUVMWP4DSI4DMQNFFAEK6FTLTHKJNQNII5UOO6W55T6K3LOV6ZITOYPQZQEVPF4N3TWJU6TWHWN4Y7CKLRH2C76D6BGZXFC7LPS2DNZGL7O2RPEJMI63YVXLEQ7W3LFOW7ZODW7QNEZ2YXELDO45EOFOSJ42ILLHVIK6HGRGRYR4FXKBBUDZ7YK4AQKASIZQWKMZOH5AIB7VDGTHBM44DJBCO47V5DVNP2UBC3QZ22GMGB7MZMGSAZN5ETAYIKH3HERCAU7SJQWGTRDM7S5Z6U7EBK53AC2RHUJIRULDB5KUPIFSOAAIVOIM7OORIWPDA23HXSLWFE6QWMXUJUSK6TRUOY7SKXBNJTHYUTNAQAVUOHXHCKATM6SWHLZL677ZZ4PCR4IFTRENFD6TDTNTXLAIATQVTAFUQPQQDJML3R57YWCXZPP7CCVJ244ZX2ZBJ3XAJCTDWLVJF3RVV5J3AJYYMFY",
          },
        };
        instance.bookPost(options, function (error) {
          if (error) throw error;
          expect().to.be();
        });
        done();
      });
    });
    describe("ratePrebook", function () {
      it("should call ratePrebook successfully", function (done) {
        let options = {
          body: {
            sessionId:
              "GIYDEMZNGAZS2MJVPQZDAMRTFUYDGLJRGZ6DC7BRGIWDS7CNIF6HYMLEMRWV6Z3EKNXGC",
            rateId:
              "2_4AJJDS635YOKR4HO6LMEPTCNH5MO3ALKOOQBIMRW7XM6UMOC7TNFPJPYOJTLBUVMWP4DSI4DMQNFFAEK6FTLTHKJNQNII5UOO6W55T6K3LOV6ZITOYPQZQEVPF4N3TWJU6TWHWN4Y7CKLRH2C76D6BGZXFC7LPS2DNZGL7O2RPEJMI63YVXLEQ7W3LFOW7ZODW7QNEZ2YXELDO45EOFOSJ42ILLHVIK6HGRGRYR4FXKBBUDZ7YK4AQKASIZQWKMZOH5AIB7VDGTHBM44DJBCO47V5DVNP2UBC3QZ22GMGB7MZMGSAZN5ETAYIKH3HERCAU7SJQWGTRDM7S5Z6U7EBK53AC2RHUJIRULDB5KUPIFSOAAIVOIM7OORIWPDA23HXSLWFE6QWMXUJUSK6TRUOY7SKXBNJTHYUTNAQAVUOHXHCKATM6SWHLZL677ZZ4PCR4IFTRENFD6TDTNTXLAIATQVTAFUQPQQDJML3R57YWCXZPP7CCVJ244ZX2ZBJ3XAJCTDWLVJF3RVV5J3AJYYMFY",
          },
        };
        instance.prebookPost(options, function (error) {
          if (error) throw error;
          expect().to.be();
        });
        done();
      });
    });
  });
});
