//
// BookingRetrieve200ResponseDataContact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BookingRetrieve200ResponseDataContact: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var firstName: String?
    public var lastName: String?

    public init(email: String? = nil, firstName: String? = nil, lastName: String? = nil) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case firstName
        case lastName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
    }
}

