//
// GetData200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetData200ResponseDataInner: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var hotelDescription: String?
    public var hotelImportantInformation: String?
    public var currency: String?
    public var country: String?
    public var city: String?
    public var location: GetData200ResponseDataInnerLocation?
    public var address: String?
    public var zip: String?
    public var isClosed: Bool?
    public var creditcardRequired: Bool?

    public init(id: Int? = nil, name: String? = nil, hotelDescription: String? = nil, hotelImportantInformation: String? = nil, currency: String? = nil, country: String? = nil, city: String? = nil, location: GetData200ResponseDataInnerLocation? = nil, address: String? = nil, zip: String? = nil, isClosed: Bool? = nil, creditcardRequired: Bool? = nil) {
        self.id = id
        self.name = name
        self.hotelDescription = hotelDescription
        self.hotelImportantInformation = hotelImportantInformation
        self.currency = currency
        self.country = country
        self.city = city
        self.location = location
        self.address = address
        self.zip = zip
        self.isClosed = isClosed
        self.creditcardRequired = creditcardRequired
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case hotelDescription = "hotel_description"
        case hotelImportantInformation = "hotel_important_information"
        case currency
        case country
        case city
        case location
        case address
        case zip
        case isClosed = "is_closed"
        case creditcardRequired = "creditcard_required"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(hotelDescription, forKey: .hotelDescription)
        try container.encodeIfPresent(hotelImportantInformation, forKey: .hotelImportantInformation)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(zip, forKey: .zip)
        try container.encodeIfPresent(isClosed, forKey: .isClosed)
        try container.encodeIfPresent(creditcardRequired, forKey: .creditcardRequired)
    }
}

