//
// HotelsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HotelsPostRequest: Codable, JSONEncodable, Hashable {

    public var checkin: String?
    public var checkout: String?
    public var latitude: Double?
    public var longitude: Double?
    public var country: String?
    public var distance: Int?
    public var adults: Int?
    public var children: String?
    public var currency: String?
    public var guestNationality: String?

    public init(checkin: String? = nil, checkout: String? = nil, latitude: Double? = nil, longitude: Double? = nil, country: String? = nil, distance: Int? = nil, adults: Int? = nil, children: String? = nil, currency: String? = nil, guestNationality: String? = nil) {
        self.checkin = checkin
        self.checkout = checkout
        self.latitude = latitude
        self.longitude = longitude
        self.country = country
        self.distance = distance
        self.adults = adults
        self.children = children
        self.currency = currency
        self.guestNationality = guestNationality
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case checkin
        case checkout
        case latitude
        case longitude
        case country
        case distance
        case adults
        case children
        case currency
        case guestNationality
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(checkin, forKey: .checkin)
        try container.encodeIfPresent(checkout, forKey: .checkout)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(distance, forKey: .distance)
        try container.encodeIfPresent(adults, forKey: .adults)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(guestNationality, forKey: .guestNationality)
    }
}

