//
// HotelsSearchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HotelsSearchRequest: Codable, JSONEncodable, Hashable {

    public var adults: Double?
    public var checkin: String?
    public var checkout: String?
    public var children: String?
    public var currency: String?
    public var guestNationality: String?
    public var hotelIds: [String]?

    public init(adults: Double? = nil, checkin: String? = nil, checkout: String? = nil, children: String? = nil, currency: String? = nil, guestNationality: String? = nil, hotelIds: [String]? = nil) {
        self.adults = adults
        self.checkin = checkin
        self.checkout = checkout
        self.children = children
        self.currency = currency
        self.guestNationality = guestNationality
        self.hotelIds = hotelIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case adults
        case checkin
        case checkout
        case children
        case currency
        case guestNationality
        case hotelIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(adults, forKey: .adults)
        try container.encodeIfPresent(checkin, forKey: .checkin)
        try container.encodeIfPresent(checkout, forKey: .checkout)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(guestNationality, forKey: .guestNationality)
        try container.encodeIfPresent(hotelIds, forKey: .hotelIds)
    }
}

