//
// HotelsSearch200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HotelsSearch200Response: Codable, JSONEncodable, Hashable {

    public var data: [HotelsSearch200ResponseDataInner]?
    public var sessionId: String?

    public init(data: [HotelsSearch200ResponseDataInner]? = nil, sessionId: String? = nil) {
        self.data = data
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case sessionId = "session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
    }
}

