//
// RatePrebook200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatePrebook200ResponseData: Codable, JSONEncodable, Hashable {

    public var currency: String?
    public var hotelId: String?
    public var prebookId: String?
    public var price: Double?
    public var roomTypes: [RatePrebook200ResponseDataRoomTypesInner]?

    public init(currency: String? = nil, hotelId: String? = nil, prebookId: String? = nil, price: Double? = nil, roomTypes: [RatePrebook200ResponseDataRoomTypesInner]? = nil) {
        self.currency = currency
        self.hotelId = hotelId
        self.prebookId = prebookId
        self.price = price
        self.roomTypes = roomTypes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case hotelId
        case prebookId
        case price
        case roomTypes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(hotelId, forKey: .hotelId)
        try container.encodeIfPresent(prebookId, forKey: .prebookId)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(roomTypes, forKey: .roomTypes)
    }
}

