//
// RateBook200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RateBook200ResponseData: Codable, JSONEncodable, Hashable {

    public var bookedRooms: [RateBook200ResponseDataBookedRoomsInner]?
    public var bookingId: String?
    public var cancellation: RateBook200ResponseDataCancellation?
    public var cancellationPolicies: RateBook200ResponseDataCancellationPolicies?
    public var contact: RateBook200ResponseDataContact?
    public var createdAt: String?
    public var end: String?
    public var hotel: RateBook200ResponseDataHotel?
    public var hotelConfirmationCode: String?
    public var notes: RateBook200ResponseDataNotes?
    public var start: String?
    public var status: String?

    public init(bookedRooms: [RateBook200ResponseDataBookedRoomsInner]? = nil, bookingId: String? = nil, cancellation: RateBook200ResponseDataCancellation? = nil, cancellationPolicies: RateBook200ResponseDataCancellationPolicies? = nil, contact: RateBook200ResponseDataContact? = nil, createdAt: String? = nil, end: String? = nil, hotel: RateBook200ResponseDataHotel? = nil, hotelConfirmationCode: String? = nil, notes: RateBook200ResponseDataNotes? = nil, start: String? = nil, status: String? = nil) {
        self.bookedRooms = bookedRooms
        self.bookingId = bookingId
        self.cancellation = cancellation
        self.cancellationPolicies = cancellationPolicies
        self.contact = contact
        self.createdAt = createdAt
        self.end = end
        self.hotel = hotel
        self.hotelConfirmationCode = hotelConfirmationCode
        self.notes = notes
        self.start = start
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bookedRooms
        case bookingId
        case cancellation
        case cancellationPolicies
        case contact
        case createdAt
        case end
        case hotel
        case hotelConfirmationCode
        case notes
        case start
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bookedRooms, forKey: .bookedRooms)
        try container.encodeIfPresent(bookingId, forKey: .bookingId)
        try container.encodeIfPresent(cancellation, forKey: .cancellation)
        try container.encodeIfPresent(cancellationPolicies, forKey: .cancellationPolicies)
        try container.encodeIfPresent(contact, forKey: .contact)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(end, forKey: .end)
        try container.encodeIfPresent(hotel, forKey: .hotel)
        try container.encodeIfPresent(hotelConfirmationCode, forKey: .hotelConfirmationCode)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(start, forKey: .start)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

