//
// RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies: Codable, JSONEncodable, Hashable {

    public var cancelPolicyInfos: [RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner]?
    public var hotelRemarks: [AnyCodable]?
    public var refundableTag: String?

    public init(cancelPolicyInfos: [RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner]? = nil, hotelRemarks: [AnyCodable]? = nil, refundableTag: String? = nil) {
        self.cancelPolicyInfos = cancelPolicyInfos
        self.hotelRemarks = hotelRemarks
        self.refundableTag = refundableTag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cancelPolicyInfos
        case hotelRemarks
        case refundableTag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cancelPolicyInfos, forKey: .cancelPolicyInfos)
        try container.encodeIfPresent(hotelRemarks, forKey: .hotelRemarks)
        try container.encodeIfPresent(refundableTag, forKey: .refundableTag)
    }
}

