//
// RateBook200ResponseDataBookedRoomsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RateBook200ResponseDataBookedRoomsInner: Codable, JSONEncodable, Hashable {

    public var adults: Double?
    public var children: Double?
    public var rate: RateBook200ResponseDataBookedRoomsInnerRate?
    public var roomType: RateBook200ResponseDataBookedRoomsInnerRoomType?

    public init(adults: Double? = nil, children: Double? = nil, rate: RateBook200ResponseDataBookedRoomsInnerRate? = nil, roomType: RateBook200ResponseDataBookedRoomsInnerRoomType? = nil) {
        self.adults = adults
        self.children = children
        self.rate = rate
        self.roomType = roomType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case adults
        case children
        case rate
        case roomType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(adults, forKey: .adults)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(rate, forKey: .rate)
        try container.encodeIfPresent(roomType, forKey: .roomType)
    }
}

