//
// RatePrebook200ResponseDataRoomTypesInnerRatesInnerRetailRate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatePrebook200ResponseDataRoomTypesInnerRatesInnerRetailRate: Codable, JSONEncodable, Hashable {

    public var taxesAndFees: [RatePrebook200ResponseDataRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner]?
    public var total: [RatePrebook200ResponseDataRoomTypesInnerRatesInnerRetailRateTotalInner]?

    public init(taxesAndFees: [RatePrebook200ResponseDataRoomTypesInnerRatesInnerRetailRateTaxesAndFeesInner]? = nil, total: [RatePrebook200ResponseDataRoomTypesInnerRatesInnerRetailRateTotalInner]? = nil) {
        self.taxesAndFees = taxesAndFees
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taxesAndFees
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(taxesAndFees, forKey: .taxesAndFees)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

