/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BookingRetrieve200ResponseDataCancellationPolicies
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-10T16:56:49.845+01:00[Africa/Casablanca]")
public class BookingRetrieve200ResponseDataCancellationPolicies {
  public static final String SERIALIZED_NAME_CANCEL_POLICY_INFOS = "cancelPolicyInfos";
  @SerializedName(SERIALIZED_NAME_CANCEL_POLICY_INFOS)
  private Object cancelPolicyInfos = null;

  public static final String SERIALIZED_NAME_HOTEL_REMARKS = "hotelRemarks";
  @SerializedName(SERIALIZED_NAME_HOTEL_REMARKS)
  private Object hotelRemarks = null;

  public BookingRetrieve200ResponseDataCancellationPolicies() {
  }

  public BookingRetrieve200ResponseDataCancellationPolicies cancelPolicyInfos(Object cancelPolicyInfos) {
    
    this.cancelPolicyInfos = cancelPolicyInfos;
    return this;
  }

   /**
   * Get cancelPolicyInfos
   * @return cancelPolicyInfos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getCancelPolicyInfos() {
    return cancelPolicyInfos;
  }


  public void setCancelPolicyInfos(Object cancelPolicyInfos) {
    this.cancelPolicyInfos = cancelPolicyInfos;
  }


  public BookingRetrieve200ResponseDataCancellationPolicies hotelRemarks(Object hotelRemarks) {
    
    this.hotelRemarks = hotelRemarks;
    return this;
  }

   /**
   * Get hotelRemarks
   * @return hotelRemarks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHotelRemarks() {
    return hotelRemarks;
  }


  public void setHotelRemarks(Object hotelRemarks) {
    this.hotelRemarks = hotelRemarks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingRetrieve200ResponseDataCancellationPolicies bookingRetrieve200ResponseDataCancellationPolicies = (BookingRetrieve200ResponseDataCancellationPolicies) o;
    return Objects.equals(this.cancelPolicyInfos, bookingRetrieve200ResponseDataCancellationPolicies.cancelPolicyInfos) &&
        Objects.equals(this.hotelRemarks, bookingRetrieve200ResponseDataCancellationPolicies.hotelRemarks);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancelPolicyInfos, hotelRemarks);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookingRetrieve200ResponseDataCancellationPolicies {\n");
    sb.append("    cancelPolicyInfos: ").append(toIndentedString(cancelPolicyInfos)).append("\n");
    sb.append("    hotelRemarks: ").append(toIndentedString(hotelRemarks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cancelPolicyInfos");
    openapiFields.add("hotelRemarks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BookingRetrieve200ResponseDataCancellationPolicies
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BookingRetrieve200ResponseDataCancellationPolicies.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BookingRetrieve200ResponseDataCancellationPolicies is not found in the empty JSON string", BookingRetrieve200ResponseDataCancellationPolicies.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BookingRetrieve200ResponseDataCancellationPolicies.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BookingRetrieve200ResponseDataCancellationPolicies` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BookingRetrieve200ResponseDataCancellationPolicies.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BookingRetrieve200ResponseDataCancellationPolicies' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BookingRetrieve200ResponseDataCancellationPolicies> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BookingRetrieve200ResponseDataCancellationPolicies.class));

       return (TypeAdapter<T>) new TypeAdapter<BookingRetrieve200ResponseDataCancellationPolicies>() {
           @Override
           public void write(JsonWriter out, BookingRetrieve200ResponseDataCancellationPolicies value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BookingRetrieve200ResponseDataCancellationPolicies read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BookingRetrieve200ResponseDataCancellationPolicies given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BookingRetrieve200ResponseDataCancellationPolicies
  * @throws IOException if the JSON string is invalid with respect to BookingRetrieve200ResponseDataCancellationPolicies
  */
  public static BookingRetrieve200ResponseDataCancellationPolicies fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BookingRetrieve200ResponseDataCancellationPolicies.class);
  }

 /**
  * Convert an instance of BookingRetrieve200ResponseDataCancellationPolicies to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

