/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.BookingRetrieve200ResponseDataBookedRoomsInnerRateRetailRate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BookingRetrieve200ResponseDataBookedRoomsInnerRate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-10T16:56:49.845+01:00[Africa/Casablanca]")
public class BookingRetrieve200ResponseDataBookedRoomsInnerRate {
  public static final String SERIALIZED_NAME_MAX_OCCUPANCY = "maxOccupancy";
  @SerializedName(SERIALIZED_NAME_MAX_OCCUPANCY)
  private BigDecimal maxOccupancy;

  public static final String SERIALIZED_NAME_RETAIL_RATE = "retailRate";
  @SerializedName(SERIALIZED_NAME_RETAIL_RATE)
  private BookingRetrieve200ResponseDataBookedRoomsInnerRateRetailRate retailRate;

  public BookingRetrieve200ResponseDataBookedRoomsInnerRate() {
  }

  public BookingRetrieve200ResponseDataBookedRoomsInnerRate maxOccupancy(BigDecimal maxOccupancy) {
    
    this.maxOccupancy = maxOccupancy;
    return this;
  }

   /**
   * Get maxOccupancy
   * @return maxOccupancy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public BigDecimal getMaxOccupancy() {
    return maxOccupancy;
  }


  public void setMaxOccupancy(BigDecimal maxOccupancy) {
    this.maxOccupancy = maxOccupancy;
  }


  public BookingRetrieve200ResponseDataBookedRoomsInnerRate retailRate(BookingRetrieve200ResponseDataBookedRoomsInnerRateRetailRate retailRate) {
    
    this.retailRate = retailRate;
    return this;
  }

   /**
   * Get retailRate
   * @return retailRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BookingRetrieve200ResponseDataBookedRoomsInnerRateRetailRate getRetailRate() {
    return retailRate;
  }


  public void setRetailRate(BookingRetrieve200ResponseDataBookedRoomsInnerRateRetailRate retailRate) {
    this.retailRate = retailRate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingRetrieve200ResponseDataBookedRoomsInnerRate bookingRetrieve200ResponseDataBookedRoomsInnerRate = (BookingRetrieve200ResponseDataBookedRoomsInnerRate) o;
    return Objects.equals(this.maxOccupancy, bookingRetrieve200ResponseDataBookedRoomsInnerRate.maxOccupancy) &&
        Objects.equals(this.retailRate, bookingRetrieve200ResponseDataBookedRoomsInnerRate.retailRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxOccupancy, retailRate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookingRetrieve200ResponseDataBookedRoomsInnerRate {\n");
    sb.append("    maxOccupancy: ").append(toIndentedString(maxOccupancy)).append("\n");
    sb.append("    retailRate: ").append(toIndentedString(retailRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("maxOccupancy");
    openapiFields.add("retailRate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BookingRetrieve200ResponseDataBookedRoomsInnerRate
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BookingRetrieve200ResponseDataBookedRoomsInnerRate.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BookingRetrieve200ResponseDataBookedRoomsInnerRate is not found in the empty JSON string", BookingRetrieve200ResponseDataBookedRoomsInnerRate.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BookingRetrieve200ResponseDataBookedRoomsInnerRate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BookingRetrieve200ResponseDataBookedRoomsInnerRate` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `retailRate`
      if (jsonObj.get("retailRate") != null && !jsonObj.get("retailRate").isJsonNull()) {
        BookingRetrieve200ResponseDataBookedRoomsInnerRateRetailRate.validateJsonObject(jsonObj.getAsJsonObject("retailRate"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BookingRetrieve200ResponseDataBookedRoomsInnerRate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BookingRetrieve200ResponseDataBookedRoomsInnerRate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BookingRetrieve200ResponseDataBookedRoomsInnerRate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BookingRetrieve200ResponseDataBookedRoomsInnerRate.class));

       return (TypeAdapter<T>) new TypeAdapter<BookingRetrieve200ResponseDataBookedRoomsInnerRate>() {
           @Override
           public void write(JsonWriter out, BookingRetrieve200ResponseDataBookedRoomsInnerRate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BookingRetrieve200ResponseDataBookedRoomsInnerRate read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BookingRetrieve200ResponseDataBookedRoomsInnerRate given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BookingRetrieve200ResponseDataBookedRoomsInnerRate
  * @throws IOException if the JSON string is invalid with respect to BookingRetrieve200ResponseDataBookedRoomsInnerRate
  */
  public static BookingRetrieve200ResponseDataBookedRoomsInnerRate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BookingRetrieve200ResponseDataBookedRoomsInnerRate.class);
  }

 /**
  * Convert an instance of BookingRetrieve200ResponseDataBookedRoomsInnerRate to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

