/*
 * Lite API
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.GetData200ResponseDataInnerLocation;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetData200ResponseDataInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-22T15:58:41.172985+01:00[Africa/Casablanca]")
public class GetData200ResponseDataInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_HOTEL_DESCRIPTION = "hotel_description";
  @SerializedName(SERIALIZED_NAME_HOTEL_DESCRIPTION)
  private String hotelDescription;

  public static final String SERIALIZED_NAME_HOTEL_IMPORTANT_INFORMATION = "hotel_important_information";
  @SerializedName(SERIALIZED_NAME_HOTEL_IMPORTANT_INFORMATION)
  private String hotelImportantInformation;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private GetData200ResponseDataInnerLocation location;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_ZIP = "zip";
  @SerializedName(SERIALIZED_NAME_ZIP)
  private String zip;

  public static final String SERIALIZED_NAME_IS_CLOSED = "is_closed";
  @SerializedName(SERIALIZED_NAME_IS_CLOSED)
  private Boolean isClosed;

  public static final String SERIALIZED_NAME_CREDITCARD_REQUIRED = "creditcard_required";
  @SerializedName(SERIALIZED_NAME_CREDITCARD_REQUIRED)
  private Boolean creditcardRequired;

  public GetData200ResponseDataInner() {
  }

  public GetData200ResponseDataInner id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public GetData200ResponseDataInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public GetData200ResponseDataInner hotelDescription(String hotelDescription) {
    
    this.hotelDescription = hotelDescription;
    return this;
  }

   /**
   * Get hotelDescription
   * @return hotelDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHotelDescription() {
    return hotelDescription;
  }


  public void setHotelDescription(String hotelDescription) {
    this.hotelDescription = hotelDescription;
  }


  public GetData200ResponseDataInner hotelImportantInformation(String hotelImportantInformation) {
    
    this.hotelImportantInformation = hotelImportantInformation;
    return this;
  }

   /**
   * Get hotelImportantInformation
   * @return hotelImportantInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHotelImportantInformation() {
    return hotelImportantInformation;
  }


  public void setHotelImportantInformation(String hotelImportantInformation) {
    this.hotelImportantInformation = hotelImportantInformation;
  }


  public GetData200ResponseDataInner currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public GetData200ResponseDataInner country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public GetData200ResponseDataInner city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public GetData200ResponseDataInner location(GetData200ResponseDataInnerLocation location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GetData200ResponseDataInnerLocation getLocation() {
    return location;
  }


  public void setLocation(GetData200ResponseDataInnerLocation location) {
    this.location = location;
  }


  public GetData200ResponseDataInner address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public GetData200ResponseDataInner zip(String zip) {
    
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getZip() {
    return zip;
  }


  public void setZip(String zip) {
    this.zip = zip;
  }


  public GetData200ResponseDataInner isClosed(Boolean isClosed) {
    
    this.isClosed = isClosed;
    return this;
  }

   /**
   * Get isClosed
   * @return isClosed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsClosed() {
    return isClosed;
  }


  public void setIsClosed(Boolean isClosed) {
    this.isClosed = isClosed;
  }


  public GetData200ResponseDataInner creditcardRequired(Boolean creditcardRequired) {
    
    this.creditcardRequired = creditcardRequired;
    return this;
  }

   /**
   * Get creditcardRequired
   * @return creditcardRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCreditcardRequired() {
    return creditcardRequired;
  }


  public void setCreditcardRequired(Boolean creditcardRequired) {
    this.creditcardRequired = creditcardRequired;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetData200ResponseDataInner getData200ResponseDataInner = (GetData200ResponseDataInner) o;
    return Objects.equals(this.id, getData200ResponseDataInner.id) &&
        Objects.equals(this.name, getData200ResponseDataInner.name) &&
        Objects.equals(this.hotelDescription, getData200ResponseDataInner.hotelDescription) &&
        Objects.equals(this.hotelImportantInformation, getData200ResponseDataInner.hotelImportantInformation) &&
        Objects.equals(this.currency, getData200ResponseDataInner.currency) &&
        Objects.equals(this.country, getData200ResponseDataInner.country) &&
        Objects.equals(this.city, getData200ResponseDataInner.city) &&
        Objects.equals(this.location, getData200ResponseDataInner.location) &&
        Objects.equals(this.address, getData200ResponseDataInner.address) &&
        Objects.equals(this.zip, getData200ResponseDataInner.zip) &&
        Objects.equals(this.isClosed, getData200ResponseDataInner.isClosed) &&
        Objects.equals(this.creditcardRequired, getData200ResponseDataInner.creditcardRequired);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, hotelDescription, hotelImportantInformation, currency, country, city, location, address, zip, isClosed, creditcardRequired);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetData200ResponseDataInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    hotelDescription: ").append(toIndentedString(hotelDescription)).append("\n");
    sb.append("    hotelImportantInformation: ").append(toIndentedString(hotelImportantInformation)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    isClosed: ").append(toIndentedString(isClosed)).append("\n");
    sb.append("    creditcardRequired: ").append(toIndentedString(creditcardRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("hotel_description");
    openapiFields.add("hotel_important_information");
    openapiFields.add("currency");
    openapiFields.add("country");
    openapiFields.add("city");
    openapiFields.add("location");
    openapiFields.add("address");
    openapiFields.add("zip");
    openapiFields.add("is_closed");
    openapiFields.add("creditcard_required");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetData200ResponseDataInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GetData200ResponseDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetData200ResponseDataInner is not found in the empty JSON string", GetData200ResponseDataInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetData200ResponseDataInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetData200ResponseDataInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("hotel_description") != null && !jsonObj.get("hotel_description").isJsonNull()) && !jsonObj.get("hotel_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hotel_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hotel_description").toString()));
      }
      if ((jsonObj.get("hotel_important_information") != null && !jsonObj.get("hotel_important_information").isJsonNull()) && !jsonObj.get("hotel_important_information").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hotel_important_information` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hotel_important_information").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      if ((jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) && !jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      // validate the optional field `location`
      if (jsonObj.get("location") != null && !jsonObj.get("location").isJsonNull()) {
        GetData200ResponseDataInnerLocation.validateJsonObject(jsonObj.getAsJsonObject("location"));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
      if ((jsonObj.get("zip") != null && !jsonObj.get("zip").isJsonNull()) && !jsonObj.get("zip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `zip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zip").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetData200ResponseDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetData200ResponseDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetData200ResponseDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetData200ResponseDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetData200ResponseDataInner>() {
           @Override
           public void write(JsonWriter out, GetData200ResponseDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetData200ResponseDataInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetData200ResponseDataInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetData200ResponseDataInner
  * @throws IOException if the JSON string is invalid with respect to GetData200ResponseDataInner
  */
  public static GetData200ResponseDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetData200ResponseDataInner.class);
  }

 /**
  * Convert an instance of GetData200ResponseDataInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

