/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-10T16:56:49.845+01:00[Africa/Casablanca]")
public class RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies {
  public static final String SERIALIZED_NAME_CANCEL_POLICY_INFOS = "cancelPolicyInfos";
  @SerializedName(SERIALIZED_NAME_CANCEL_POLICY_INFOS)
  private List<RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner> cancelPolicyInfos = null;

  public static final String SERIALIZED_NAME_HOTEL_REMARKS = "hotelRemarks";
  @SerializedName(SERIALIZED_NAME_HOTEL_REMARKS)
  private List<Object> hotelRemarks = null;

  public static final String SERIALIZED_NAME_REFUNDABLE_TAG = "refundableTag";
  @SerializedName(SERIALIZED_NAME_REFUNDABLE_TAG)
  private String refundableTag;

  public RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies() {
  }

  public RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies cancelPolicyInfos(List<RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner> cancelPolicyInfos) {
    
    this.cancelPolicyInfos = cancelPolicyInfos;
    return this;
  }

  public RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies addCancelPolicyInfosItem(RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner cancelPolicyInfosItem) {
    if (this.cancelPolicyInfos == null) {
      this.cancelPolicyInfos = new ArrayList<>();
    }
    this.cancelPolicyInfos.add(cancelPolicyInfosItem);
    return this;
  }

   /**
   * Get cancelPolicyInfos
   * @return cancelPolicyInfos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"amount\":137.02458727256,\"cancelTime\":\"2023-01-10\",\"type\":\"amount\"}]", value = "")

  public List<RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner> getCancelPolicyInfos() {
    return cancelPolicyInfos;
  }


  public void setCancelPolicyInfos(List<RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner> cancelPolicyInfos) {
    this.cancelPolicyInfos = cancelPolicyInfos;
  }


  public RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies hotelRemarks(List<Object> hotelRemarks) {
    
    this.hotelRemarks = hotelRemarks;
    return this;
  }

  public RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies addHotelRemarksItem(Object hotelRemarksItem) {
    if (this.hotelRemarks == null) {
      this.hotelRemarks = new ArrayList<>();
    }
    this.hotelRemarks.add(hotelRemarksItem);
    return this;
  }

   /**
   * Get hotelRemarks
   * @return hotelRemarks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[]", value = "")

  public List<Object> getHotelRemarks() {
    return hotelRemarks;
  }


  public void setHotelRemarks(List<Object> hotelRemarks) {
    this.hotelRemarks = hotelRemarks;
  }


  public RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies refundableTag(String refundableTag) {
    
    this.refundableTag = refundableTag;
    return this;
  }

   /**
   * Get refundableTag
   * @return refundableTag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "RFN", value = "")

  public String getRefundableTag() {
    return refundableTag;
  }


  public void setRefundableTag(String refundableTag) {
    this.refundableTag = refundableTag;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies ratePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies = (RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies) o;
    return Objects.equals(this.cancelPolicyInfos, ratePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.cancelPolicyInfos) &&
        Objects.equals(this.hotelRemarks, ratePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.hotelRemarks) &&
        Objects.equals(this.refundableTag, ratePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.refundableTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancelPolicyInfos, hotelRemarks, refundableTag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies {\n");
    sb.append("    cancelPolicyInfos: ").append(toIndentedString(cancelPolicyInfos)).append("\n");
    sb.append("    hotelRemarks: ").append(toIndentedString(hotelRemarks)).append("\n");
    sb.append("    refundableTag: ").append(toIndentedString(refundableTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cancelPolicyInfos");
    openapiFields.add("hotelRemarks");
    openapiFields.add("refundableTag");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies is not found in the empty JSON string", RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("cancelPolicyInfos") != null && !jsonObj.get("cancelPolicyInfos").isJsonNull()) {
        JsonArray jsonArraycancelPolicyInfos = jsonObj.getAsJsonArray("cancelPolicyInfos");
        if (jsonArraycancelPolicyInfos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("cancelPolicyInfos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `cancelPolicyInfos` to be an array in the JSON string but got `%s`", jsonObj.get("cancelPolicyInfos").toString()));
          }

          // validate the optional field `cancelPolicyInfos` (array)
          for (int i = 0; i < jsonArraycancelPolicyInfos.size(); i++) {
            RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesCancelPolicyInfosInner.validateJsonObject(jsonArraycancelPolicyInfos.get(i).getAsJsonObject());
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("hotelRemarks") != null && !jsonObj.get("hotelRemarks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `hotelRemarks` to be an array in the JSON string but got `%s`", jsonObj.get("hotelRemarks").toString()));
      }
      if ((jsonObj.get("refundableTag") != null && !jsonObj.get("refundableTag").isJsonNull()) && !jsonObj.get("refundableTag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refundableTag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refundableTag").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.class));

       return (TypeAdapter<T>) new TypeAdapter<RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies>() {
           @Override
           public void write(JsonWriter out, RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies
  * @throws IOException if the JSON string is invalid with respect to RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies
  */
  public static RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies.class);
  }

 /**
  * Convert an instance of RatePrebook200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

