/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RatePrebook200ResponseDataRoomTypesInnerRatesInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RatePrebook200ResponseDataRoomTypesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-10T16:56:49.845+01:00[Africa/Casablanca]")
public class RatePrebook200ResponseDataRoomTypesInner {
  public static final String SERIALIZED_NAME_MAX_OCCUPANCY = "maxOccupancy";
  @SerializedName(SERIALIZED_NAME_MAX_OCCUPANCY)
  private BigDecimal maxOccupancy;

  public static final String SERIALIZED_NAME_RATES = "rates";
  @SerializedName(SERIALIZED_NAME_RATES)
  private List<RatePrebook200ResponseDataRoomTypesInnerRatesInner> rates = null;

  public RatePrebook200ResponseDataRoomTypesInner() {
  }

  public RatePrebook200ResponseDataRoomTypesInner maxOccupancy(BigDecimal maxOccupancy) {
    
    this.maxOccupancy = maxOccupancy;
    return this;
  }

   /**
   * Get maxOccupancy
   * @return maxOccupancy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public BigDecimal getMaxOccupancy() {
    return maxOccupancy;
  }


  public void setMaxOccupancy(BigDecimal maxOccupancy) {
    this.maxOccupancy = maxOccupancy;
  }


  public RatePrebook200ResponseDataRoomTypesInner rates(List<RatePrebook200ResponseDataRoomTypesInnerRatesInner> rates) {
    
    this.rates = rates;
    return this;
  }

  public RatePrebook200ResponseDataRoomTypesInner addRatesItem(RatePrebook200ResponseDataRoomTypesInnerRatesInner ratesItem) {
    if (this.rates == null) {
      this.rates = new ArrayList<>();
    }
    this.rates.add(ratesItem);
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"cancellationPolicies\":{\"cancelPolicyInfos\":[{\"amount\":137.02458727256,\"cancelTime\":\"2023-01-10\",\"type\":\"amount\"}],\"hotelRemarks\":[],\"refundableTag\":\"RFN\"},\"maxOccupancy\":1,\"name\":\"Run of House/1 Bed - Room Only\",\"rateId\":\"G4ZDONJWMUZDANTGGY3DEMBWHA3GMNZVG4ZTMNJSMYZTCMRQGYZDMNJWGR6DCIZSGAZDGMBRGE2XYMRQGIZTAMJRGZ6GK3S7KVJXYTKBPRCVKUT4GFATAQ34GE3DSOD4IJIWCOKWPQYTMNRTGYZDQOBSGYZDONCNJ5JE2IZRGEZDSMZZEMZTAOBNGEYTEOJTHF6FERSOPQZDAMRTGAYTCMD4GV6DCMZXGAZCGUSPENJEMTRDGIYDEMZNGAYS2MJQ\",\"retailRate\":{\"taxesAndFees\":[{\"amount\":0,\"currency\":\"EUR\",\"description\":\"roomTax\",\"included\":true},{\"amount\":0,\"currency\":\"EUR\",\"description\":\"salesTax\",\"included\":true},{\"amount\":0,\"currency\":\"EUR\",\"description\":\"otherCharges\",\"included\":true}],\"total\":[{\"amount\":137.02458727256,\"currency\":\"EUR\"}]}}]", value = "")

  public List<RatePrebook200ResponseDataRoomTypesInnerRatesInner> getRates() {
    return rates;
  }


  public void setRates(List<RatePrebook200ResponseDataRoomTypesInnerRatesInner> rates) {
    this.rates = rates;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatePrebook200ResponseDataRoomTypesInner ratePrebook200ResponseDataRoomTypesInner = (RatePrebook200ResponseDataRoomTypesInner) o;
    return Objects.equals(this.maxOccupancy, ratePrebook200ResponseDataRoomTypesInner.maxOccupancy) &&
        Objects.equals(this.rates, ratePrebook200ResponseDataRoomTypesInner.rates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxOccupancy, rates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatePrebook200ResponseDataRoomTypesInner {\n");
    sb.append("    maxOccupancy: ").append(toIndentedString(maxOccupancy)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("maxOccupancy");
    openapiFields.add("rates");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RatePrebook200ResponseDataRoomTypesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RatePrebook200ResponseDataRoomTypesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RatePrebook200ResponseDataRoomTypesInner is not found in the empty JSON string", RatePrebook200ResponseDataRoomTypesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!RatePrebook200ResponseDataRoomTypesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RatePrebook200ResponseDataRoomTypesInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("rates") != null && !jsonObj.get("rates").isJsonNull()) {
        JsonArray jsonArrayrates = jsonObj.getAsJsonArray("rates");
        if (jsonArrayrates != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rates").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `rates` to be an array in the JSON string but got `%s`", jsonObj.get("rates").toString()));
          }

          // validate the optional field `rates` (array)
          for (int i = 0; i < jsonArrayrates.size(); i++) {
            RatePrebook200ResponseDataRoomTypesInnerRatesInner.validateJsonObject(jsonArrayrates.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RatePrebook200ResponseDataRoomTypesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RatePrebook200ResponseDataRoomTypesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RatePrebook200ResponseDataRoomTypesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RatePrebook200ResponseDataRoomTypesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<RatePrebook200ResponseDataRoomTypesInner>() {
           @Override
           public void write(JsonWriter out, RatePrebook200ResponseDataRoomTypesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RatePrebook200ResponseDataRoomTypesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RatePrebook200ResponseDataRoomTypesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RatePrebook200ResponseDataRoomTypesInner
  * @throws IOException if the JSON string is invalid with respect to RatePrebook200ResponseDataRoomTypesInner
  */
  public static RatePrebook200ResponseDataRoomTypesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RatePrebook200ResponseDataRoomTypesInner.class);
  }

 /**
  * Convert an instance of RatePrebook200ResponseDataRoomTypesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

