/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.HotelsData200Response;
import org.openapitools.client.model.HotelsSearch400Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class DefaultApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for hotelsData
     * @param hotelName  (optional)
     * @param cityName  (optional)
     * @param countryCode  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @param rid  (optional)
     * @param xid  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ibis hotels in Paris France </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Connection -  <br>  * Content-Encoding -  <br>  * Content-Length -  <br>  * Date -  <br>  * x-amz-apigw-id -  <br>  * x-amzn-Remapped-Date -  <br>  * x-amzn-RequestId -  <br>  </td></tr>
        <tr><td> 400 </td><td> Retrieve hotel no availability </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Content-Length -  <br>  * Date -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call hotelsDataCall(String hotelName, String cityName, String countryCode, String limit, String offset, String rid, String xid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/data";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (hotelName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("hotelName", hotelName));
        }

        if (cityName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cityName", cityName));
        }

        if (countryCode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("countryCode", countryCode));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (rid != null) {
            localVarHeaderParams.put("rid", localVarApiClient.parameterToString(rid));
        }

        if (xid != null) {
            localVarHeaderParams.put("xid", localVarApiClient.parameterToString(xid));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call hotelsDataValidateBeforeCall(String hotelName, String cityName, String countryCode, String limit, String offset, String rid, String xid, final ApiCallback _callback) throws ApiException {
        return hotelsDataCall(hotelName, cityName, countryCode, limit, offset, rid, xid, _callback);

    }

    /**
     * hotels data
     * hotels data
     * @param hotelName  (optional)
     * @param cityName  (optional)
     * @param countryCode  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @param rid  (optional)
     * @param xid  (optional)
     * @return HotelsData200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ibis hotels in Paris France </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Connection -  <br>  * Content-Encoding -  <br>  * Content-Length -  <br>  * Date -  <br>  * x-amz-apigw-id -  <br>  * x-amzn-Remapped-Date -  <br>  * x-amzn-RequestId -  <br>  </td></tr>
        <tr><td> 400 </td><td> Retrieve hotel no availability </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Content-Length -  <br>  * Date -  <br>  </td></tr>
     </table>
     */
    public HotelsData200Response hotelsData(String hotelName, String cityName, String countryCode, String limit, String offset, String rid, String xid) throws ApiException {
        ApiResponse<HotelsData200Response> localVarResp = hotelsDataWithHttpInfo(hotelName, cityName, countryCode, limit, offset, rid, xid);
        return localVarResp.getData();
    }

    /**
     * hotels data
     * hotels data
     * @param hotelName  (optional)
     * @param cityName  (optional)
     * @param countryCode  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @param rid  (optional)
     * @param xid  (optional)
     * @return ApiResponse&lt;HotelsData200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ibis hotels in Paris France </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Connection -  <br>  * Content-Encoding -  <br>  * Content-Length -  <br>  * Date -  <br>  * x-amz-apigw-id -  <br>  * x-amzn-Remapped-Date -  <br>  * x-amzn-RequestId -  <br>  </td></tr>
        <tr><td> 400 </td><td> Retrieve hotel no availability </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Content-Length -  <br>  * Date -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<HotelsData200Response> hotelsDataWithHttpInfo(String hotelName, String cityName, String countryCode, String limit, String offset, String rid, String xid) throws ApiException {
        okhttp3.Call localVarCall = hotelsDataValidateBeforeCall(hotelName, cityName, countryCode, limit, offset, rid, xid, null);
        Type localVarReturnType = new TypeToken<HotelsData200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * hotels data (asynchronously)
     * hotels data
     * @param hotelName  (optional)
     * @param cityName  (optional)
     * @param countryCode  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @param rid  (optional)
     * @param xid  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ibis hotels in Paris France </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Connection -  <br>  * Content-Encoding -  <br>  * Content-Length -  <br>  * Date -  <br>  * x-amz-apigw-id -  <br>  * x-amzn-Remapped-Date -  <br>  * x-amzn-RequestId -  <br>  </td></tr>
        <tr><td> 400 </td><td> Retrieve hotel no availability </td><td>  * Access-Control-Allow-Credentials -  <br>  * Access-Control-Allow-Headers -  <br>  * Access-Control-Allow-Methods -  <br>  * Access-Control-Allow-Origin -  <br>  * Access-Control-Expose-Headers -  <br>  * Access-Control-Max-Age -  <br>  * Content-Length -  <br>  * Date -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call hotelsDataAsync(String hotelName, String cityName, String countryCode, String limit, String offset, String rid, String xid, final ApiCallback<HotelsData200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = hotelsDataValidateBeforeCall(hotelName, cityName, countryCode, limit, offset, rid, xid, _callback);
        Type localVarReturnType = new TypeToken<HotelsData200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
