/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.HotelRates200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies;
import org.openapitools.client.model.HotelRates200ResponseDataRoomTypesInnerRatesInnerRetailRate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HotelRates200ResponseDataRoomTypesInnerRatesInner
 */
public class HotelRates200ResponseDataRoomTypesInnerRatesInnerTest {
    private final HotelRates200ResponseDataRoomTypesInnerRatesInner model = new HotelRates200ResponseDataRoomTypesInnerRatesInner();

    /**
     * Model tests for HotelRates200ResponseDataRoomTypesInnerRatesInner
     */
    @Test
    public void testHotelRates200ResponseDataRoomTypesInnerRatesInner() {
        // TODO: test HotelRates200ResponseDataRoomTypesInnerRatesInner
    }

    /**
     * Test the property 'cancellationPolicies'
     */
    @Test
    public void cancellationPoliciesTest() {
        // TODO: test cancellationPolicies
    }

    /**
     * Test the property 'maxOccupancy'
     */
    @Test
    public void maxOccupancyTest() {
        // TODO: test maxOccupancy
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rateId'
     */
    @Test
    public void rateIdTest() {
        // TODO: test rateId
    }

    /**
     * Test the property 'retailRate'
     */
    @Test
    public void retailRateTest() {
        // TODO: test retailRate
    }

}
