/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RateBook200ResponseDataBookedRoomsInner;
import org.openapitools.client.model.RateBook200ResponseDataCancellation;
import org.openapitools.client.model.RateBook200ResponseDataCancellationPolicies;
import org.openapitools.client.model.RateBook200ResponseDataContact;
import org.openapitools.client.model.RateBook200ResponseDataHotel;
import org.openapitools.client.model.RateBook200ResponseDataNotes;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RateBook200ResponseData
 */
public class RateBook200ResponseDataTest {
    private final RateBook200ResponseData model = new RateBook200ResponseData();

    /**
     * Model tests for RateBook200ResponseData
     */
    @Test
    public void testRateBook200ResponseData() {
        // TODO: test RateBook200ResponseData
    }

    /**
     * Test the property 'bookedRooms'
     */
    @Test
    public void bookedRoomsTest() {
        // TODO: test bookedRooms
    }

    /**
     * Test the property 'bookingId'
     */
    @Test
    public void bookingIdTest() {
        // TODO: test bookingId
    }

    /**
     * Test the property 'cancellation'
     */
    @Test
    public void cancellationTest() {
        // TODO: test cancellation
    }

    /**
     * Test the property 'cancellationPolicies'
     */
    @Test
    public void cancellationPoliciesTest() {
        // TODO: test cancellationPolicies
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'hotel'
     */
    @Test
    public void hotelTest() {
        // TODO: test hotel
    }

    /**
     * Test the property 'hotelConfirmationCode'
     */
    @Test
    public void hotelConfirmationCodeTest() {
        // TODO: test hotelConfirmationCode
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
