/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner
 */
public class RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInnerTest {
    private final RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner model = new RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner();

    /**
     * Model tests for RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner
     */
    @Test
    public void testRateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner() {
        // TODO: test RateBook200ResponseDataCancellationPoliciesCancelPolicyInfosInner
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'cancelTime'
     */
    @Test
    public void cancelTimeTest() {
        // TODO: test cancelTime
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
