/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.RateBook200ResponseDataBookedRoomsInnerRateRetailRateTotal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RateBook200ResponseDataBookedRoomsInnerRateRetailRate
 */
public class RateBook200ResponseDataBookedRoomsInnerRateRetailRateTest {
    private final RateBook200ResponseDataBookedRoomsInnerRateRetailRate model = new RateBook200ResponseDataBookedRoomsInnerRateRetailRate();

    /**
     * Model tests for RateBook200ResponseDataBookedRoomsInnerRateRetailRate
     */
    @Test
    public void testRateBook200ResponseDataBookedRoomsInnerRateRetailRate() {
        // TODO: test RateBook200ResponseDataBookedRoomsInnerRateRetailRate
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
