/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.RateBook200ResponseDataHotelAddress;
import org.openapitools.client.model.RateBook200ResponseDataHotelLocation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RateBook200ResponseDataHotel
 */
public class RateBook200ResponseDataHotelTest {
    private final RateBook200ResponseDataHotel model = new RateBook200ResponseDataHotel();

    /**
     * Model tests for RateBook200ResponseDataHotel
     */
    @Test
    public void testRateBook200ResponseDataHotel() {
        // TODO: test RateBook200ResponseDataHotel
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'hotelId'
     */
    @Test
    public void hotelIdTest() {
        // TODO: test hotelId
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'starRating'
     */
    @Test
    public void starRatingTest() {
        // TODO: test starRating
    }

}
