/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RatePrebook200ResponseDataRoomTypesInnerRatesInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RatePrebook200ResponseDataRoomTypesInner
 */
public class RatePrebook200ResponseDataRoomTypesInnerTest {
    private final RatePrebook200ResponseDataRoomTypesInner model = new RatePrebook200ResponseDataRoomTypesInner();

    /**
     * Model tests for RatePrebook200ResponseDataRoomTypesInner
     */
    @Test
    public void testRatePrebook200ResponseDataRoomTypesInner() {
        // TODO: test RatePrebook200ResponseDataRoomTypesInner
    }

    /**
     * Test the property 'maxOccupancy'
     */
    @Test
    public void maxOccupancyTest() {
        // TODO: test maxOccupancy
    }

    /**
     * Test the property 'rates'
     */
    @Test
    public void ratesTest() {
        // TODO: test rates
    }

}
