/*
 * nlite API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RateBook200ResponseDataBookedRoomsInnerRateRetailRateTotal
 */
public class RateBook200ResponseDataBookedRoomsInnerRateRetailRateTotalTest {
    private final RateBook200ResponseDataBookedRoomsInnerRateRetailRateTotal model = new RateBook200ResponseDataBookedRoomsInnerRateRetailRateTotal();

    /**
     * Model tests for RateBook200ResponseDataBookedRoomsInnerRateRetailRateTotal
     */
    @Test
    public void testRateBook200ResponseDataBookedRoomsInnerRateRetailRateTotal() {
        // TODO: test RateBook200ResponseDataBookedRoomsInnerRateRetailRateTotal
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
